INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_game(score, count, title, image) VALUES (4.5, 2, 'God of War', 'https://images2.alphacoders.com/778/778340.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (3.3, 3, 'Red Dead Redemption 2', 'https://images8.alphacoders.com/958/958091.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'The Last of Us 2', 'https://images6.alphacoders.com/788/788051.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Valorant', 'https://images6.alphacoders.com/107/1072679.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'CoD Black Ops III', 'https://images2.alphacoders.com/597/597965.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Minecraft', 'https://images.alphacoders.com/963/96393.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'NFS Underground 2', 'https://images7.alphacoders.com/530/530583.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Midnight Club 3', 'https://images2.alphacoders.com/697/697015.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Rise of the Tomb Raider', 'https://images2.alphacoders.com/597/597950.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Grand Theft Auto V', 'https://images7.alphacoders.com/439/439636.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Counter Strike: Global offensive', 'https://images7.alphacoders.com/587/587593.png');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'The Witcher: Wild Hunt', 'https://images2.alphacoders.com/600/600255.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'The Elder Scrolls V: Skyrim', 'https://images7.alphacoders.com/319/319944.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Uncharted 4', 'https://images7.alphacoders.com/515/515386.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Resident Evil 4', 'https://images8.alphacoders.com/672/672729.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Mortal Kombat X', 'https://images8.alphacoders.com/597/597959.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'State of Decay 2', 'https://images5.alphacoders.com/724/724345.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Guitar Hero 3: Legends of Rock', 'https://images4.alphacoders.com/242/242928.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Final Fantasy XV', 'https://images4.alphacoders.com/109/109174.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Super Mario Odyssey', 'https://images2.alphacoders.com/854/854342.png');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Shadow of the Colossus', 'https://images3.alphacoders.com/557/55717.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'FarCry 3', 'https://images5.alphacoders.com/323/323451.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Fallout 4', 'https://images7.alphacoders.com/599/599168.png');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Days Gone', 'https://images5.alphacoders.com/745/745809.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Horizon Zero Dawn', 'https://images4.alphacoders.com/601/601157.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Gears of War 4', 'https://images8.alphacoders.com/691/691313.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Dark Souls 3', 'https://images5.alphacoders.com/609/609173.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Nioh', 'https://images8.alphacoders.com/720/720466.jpg');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Burnout Paradise', 'https://images6.alphacoders.com/484/484931.gif');
INSERT INTO tb_game(score, count, title, image) VALUES (0, 0, 'Cyberpunk 2077', 'https://images7.alphacoders.com/102/1020913.jpg');

INSERT INTO tb_score(game_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(game_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(game_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(game_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(game_id, user_id, value) VALUES (2, 3, 4.0);